### ISSUE TITLE
Use RTC clock and rtcvars at the same time?

### ISSUE THREAD

**Issue by zxpectre** [highno/rtcvars#2]
Thanks for this cool lib!
Is possible to store datetime from ntp server AND use rtcvars at the same time? Is it safe?
Maybe there is some spare space for vars at the right address.

**Comment by highno** [comment]
Thanks for the praise. Yes - using it together with ntp is perfectly safe. The ESP’s internal RTC is always running and using that memory, no matter if you are using NTP to synchronize time or not. But it uses only a very small part of that memory. The lib excludes that area and uses the remaining memory.
