### ISSUE TITLE
Unsigned Long?

### ISSUE THREAD

**Issue by bwjohns4** [highno/rtcvars#5]
How can I register an unsigned long? Can I do this without modifying the library itself?

`state.registerVar(&acrossRebootAccumulator)`

**Comment by bwjohns4** [comment]
I just cast this as a regular long like this:
`state.registerVar((long*)&acrossRebootAccumulator);`

**Comment by highno** [comment]
Great to see you found a a way. I guess that should be on my list for a new version, right?
Well, ESP32 compatibility is, too. If I only find some time...
